### ISSUE TITLE
AdamW Parameter setting problem

### ISSUE THREAD

**Issue by tongxiaozhong14** [kvpratama/unet#1]
In the training process, is the b1=0.5 of the AdamM optimizer a better choice? Can it be set to b1=0.9
If I want to use Adam optimizer in the experiment, b1 should be set to b1=0.5 or b1=0.9

**Comment by kvpratama** [comment]
I think it will depend on the dataset that you are using since beta is a hyperparameter for both Adam and AdamW. I would suggest using the default value in your first experiment and then adjust those numbers to see if you get a better result.

**Comment by tongxiaozhong14** [comment]
Thank you very much for your reply. My data sets are ISIC2017 and ISIC2016. What is the appropriate setting?

**Comment by kvpratama** [comment]
I have no experience with both ISIC2017 and ISIC2016 datasets. I have only done an experiment with ISIC2018 with the suggested value in Adam paper. As I mentioned previously, I would recommend you experiment with the suggested value first, then play with others value and see if you can get a significant improvement.
