### ISSUE TITLE
AdamW parameter settings

### ISSUE THREAD

**Issue by tongxiaozhong14** [kvpratama/unet#2]
Thank you very much for your reply. My data sets are ISIC2017 and ISIC2016. What is the appropriate setting?

**Comment by kvpratama** [comment]
I have no experience with both ISIC2017 and ISIC2016 datasets. I have only done an experiment with ISIC2018 with the suggested value in Adam paper. As I mentioned previously, I would recommend you experiment with the suggested value first, then play with others value and see if you can get a significant improvement.
